/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: zncc [OPTIONS]";

const char *gengetopt_args_info_versiontext = "Multithreaded implementation";

const char *gengetopt_args_info_description = "Simple ZNCC depthmap implementation. Looks for im0.png and im1.png in working\ndirectory. Outputs to outputs/ relative to working directory. See zncc.cpp for\ndetails.";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                   Print help and exit",
  "  -V, --version                Print version and exit",
  "      --use-gpu                Use GPU for computation.  (default=off)",
  "  -d, --maximum-disparity=INT  The maximum disparity between images.\n                                 (default=`64')",
  "  -t, --threshold=INT          The threshold used for cross-checking.\n                                 (default=`8')",
  "  -w, --window-size=INT        The length of zncc window. This parameter\n                                 represents one side of the window used for\n                                 zncc. (Block size is square of the value\n                                 specified here)  (default=`8')",
  "      --nthreads=INT           Number of threads for zncc computation.\n                                 (default=`1')",
  "  -s, --skip-depthmapping      Skip computation of disparity images. Skip\n                                 computation of disparity images. This option\n                                 will use supplied images, and if none is\n                                 supplied, looks for previously output files at\n                                 ./output/ directory. Missing files will cause\n                                 the program to terminate.  (default=off)",
  "      --image-0=STRING         Image 0 filepath",
  "      --image-1=STRING         Image 1 filepath",
  "      --shrink-by=INT          Shrink factor to downscale image. Typically set\n                                 to 1 when skipping depthmapping step.\n                                 (default=`4')",
  "\nAuthor: Kaushik Sundarajayaraman Venkat\nE-mail: speak2kaushik@gmail.com, kaushik.sv@student.oulu.fi\n",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->use_gpu_given = 0 ;
  args_info->maximum_disparity_given = 0 ;
  args_info->threshold_given = 0 ;
  args_info->window_size_given = 0 ;
  args_info->nthreads_given = 0 ;
  args_info->skip_depthmapping_given = 0 ;
  args_info->image_0_given = 0 ;
  args_info->image_1_given = 0 ;
  args_info->shrink_by_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->use_gpu_flag = 0;
  args_info->maximum_disparity_arg = 64;
  args_info->maximum_disparity_orig = NULL;
  args_info->threshold_arg = 8;
  args_info->threshold_orig = NULL;
  args_info->window_size_arg = 8;
  args_info->window_size_orig = NULL;
  args_info->nthreads_arg = 1;
  args_info->nthreads_orig = NULL;
  args_info->skip_depthmapping_flag = 0;
  args_info->image_0_arg = NULL;
  args_info->image_0_orig = NULL;
  args_info->image_1_arg = NULL;
  args_info->image_1_orig = NULL;
  args_info->shrink_by_arg = 4;
  args_info->shrink_by_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->use_gpu_help = gengetopt_args_info_help[2] ;
  args_info->maximum_disparity_help = gengetopt_args_info_help[3] ;
  args_info->threshold_help = gengetopt_args_info_help[4] ;
  args_info->window_size_help = gengetopt_args_info_help[5] ;
  args_info->nthreads_help = gengetopt_args_info_help[6] ;
  args_info->skip_depthmapping_help = gengetopt_args_info_help[7] ;
  args_info->image_0_help = gengetopt_args_info_help[8] ;
  args_info->image_1_help = gengetopt_args_info_help[9] ;
  args_info->shrink_by_help = gengetopt_args_info_help[10] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->maximum_disparity_orig));
  free_string_field (&(args_info->threshold_orig));
  free_string_field (&(args_info->window_size_orig));
  free_string_field (&(args_info->nthreads_orig));
  free_string_field (&(args_info->image_0_arg));
  free_string_field (&(args_info->image_0_orig));
  free_string_field (&(args_info->image_1_arg));
  free_string_field (&(args_info->image_1_orig));
  free_string_field (&(args_info->shrink_by_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->use_gpu_given)
    write_into_file(outfile, "use-gpu", 0, 0 );
  if (args_info->maximum_disparity_given)
    write_into_file(outfile, "maximum-disparity", args_info->maximum_disparity_orig, 0);
  if (args_info->threshold_given)
    write_into_file(outfile, "threshold", args_info->threshold_orig, 0);
  if (args_info->window_size_given)
    write_into_file(outfile, "window-size", args_info->window_size_orig, 0);
  if (args_info->nthreads_given)
    write_into_file(outfile, "nthreads", args_info->nthreads_orig, 0);
  if (args_info->skip_depthmapping_given)
    write_into_file(outfile, "skip-depthmapping", 0, 0 );
  if (args_info->image_0_given)
    write_into_file(outfile, "image-0", args_info->image_0_orig, 0);
  if (args_info->image_1_given)
    write_into_file(outfile, "image-1", args_info->image_1_orig, 0);
  if (args_info->shrink_by_given)
    write_into_file(outfile, "shrink-by", args_info->shrink_by_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "use-gpu",	0, NULL, 0 },
        { "maximum-disparity",	1, NULL, 'd' },
        { "threshold",	1, NULL, 't' },
        { "window-size",	1, NULL, 'w' },
        { "nthreads",	1, NULL, 0 },
        { "skip-depthmapping",	0, NULL, 's' },
        { "image-0",	1, NULL, 0 },
        { "image-1",	1, NULL, 0 },
        { "shrink-by",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVd:t:w:s", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'd':	/* The maximum disparity between images..  */
        
        
          if (update_arg( (void *)&(args_info->maximum_disparity_arg), 
               &(args_info->maximum_disparity_orig), &(args_info->maximum_disparity_given),
              &(local_args_info.maximum_disparity_given), optarg, 0, "64", ARG_INT,
              check_ambiguity, override, 0, 0,
              "maximum-disparity", 'd',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* The threshold used for cross-checking..  */
        
        
          if (update_arg( (void *)&(args_info->threshold_arg), 
               &(args_info->threshold_orig), &(args_info->threshold_given),
              &(local_args_info.threshold_given), optarg, 0, "8", ARG_INT,
              check_ambiguity, override, 0, 0,
              "threshold", 't',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* The length of zncc window. This parameter represents one side of the window used for zncc. (Block size is square of the value specified here).  */
        
        
          if (update_arg( (void *)&(args_info->window_size_arg), 
               &(args_info->window_size_orig), &(args_info->window_size_given),
              &(local_args_info.window_size_given), optarg, 0, "8", ARG_INT,
              check_ambiguity, override, 0, 0,
              "window-size", 'w',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Skip computation of disparity images. Skip computation of disparity images. This option will use supplied images, and if none is supplied, looks for previously output files at ./output/ directory. Missing files will cause the program to terminate..  */
        
        
          if (update_arg((void *)&(args_info->skip_depthmapping_flag), 0, &(args_info->skip_depthmapping_given),
              &(local_args_info.skip_depthmapping_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "skip-depthmapping", 's',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Use GPU for computation..  */
          if (strcmp (long_options[option_index].name, "use-gpu") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->use_gpu_flag), 0, &(args_info->use_gpu_given),
                &(local_args_info.use_gpu_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "use-gpu", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of threads for zncc computation..  */
          else if (strcmp (long_options[option_index].name, "nthreads") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->nthreads_arg), 
                 &(args_info->nthreads_orig), &(args_info->nthreads_given),
                &(local_args_info.nthreads_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "nthreads", '-',
                additional_error))
              goto failure;
          
          }
          /* Image 0 filepath.  */
          else if (strcmp (long_options[option_index].name, "image-0") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->image_0_arg), 
                 &(args_info->image_0_orig), &(args_info->image_0_given),
                &(local_args_info.image_0_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "image-0", '-',
                additional_error))
              goto failure;
          
          }
          /* Image 1 filepath.  */
          else if (strcmp (long_options[option_index].name, "image-1") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->image_1_arg), 
                 &(args_info->image_1_orig), &(args_info->image_1_given),
                &(local_args_info.image_1_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "image-1", '-',
                additional_error))
              goto failure;
          
          }
          /* Shrink factor to downscale image. Typically set to 1 when skipping depthmapping step..  */
          else if (strcmp (long_options[option_index].name, "shrink-by") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->shrink_by_arg), 
                 &(args_info->shrink_by_orig), &(args_info->shrink_by_given),
                &(local_args_info.shrink_by_given), optarg, 0, "4", ARG_INT,
                check_ambiguity, override, 0, 0,
                "shrink-by", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
